use_frameworks!

platform :ios, '10.0'

target 'ZLKeyboardManager_Example' do
  pod 'ZLKeyboardManager', :path => '../'

  target 'ZLKeyboardManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
